### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by krl** [dusk-network/dusk-kelvin-map#3]
The map implementation needs to use a balanced tree.

At the moment, sequential inserts will have a worst case complexity linear in time and space.

**Comment by vlopes11** [comment]
Agreed.

@krl Should we go for a 2-3 map or just a balanced binary tree would be enough? What do you think?

**Comment by vlopes11** [comment]
I checked, and I believe the 2-3 tree will be far more complex to implement compared to the balanced BST.

I'll go for the balanced BST. Later on we can compare the performance with a 2-3 and decide over the tradeoffs
