### ISSUE TITLE
API should not clone or have to take closures.

### ISSUE THREAD

**Issue by krl** [dusk-network/dusk-kelvin-map#4]
The `get` and `get_mut` functions should not clone or require a closure.

One way of doing this would be to change the return type to a wrapper type, containing a Branch or BranchMut, that derefs to the Value of the KV pair at the tip of the branch.

**Comment by vlopes11** [comment]
Agreed. We must find a solution so the signature is `fn get(&self, key: &K) -> Result<Option<&V>>` as in the standard:

https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.get
